### ISSUE TITLE
calc_pos_in_canvas()修正？案

### ISSUE THREAD

**Issue by nakamo326** [nakamo326/term3d#9]
https://github.com/nakamo326/term3d/blob/823c12851b10c0941ddba456c834610a838f7df2/srcs/draw.c#L3

ここのdim sizeはdoubleで受け取ったほうが値が正確に出そうじゃないですか？
見当違いだったらご無礼😅

**Comment by ToYeah** [comment]
doubleと演算するときにdoubleに暗黙キャストされてるはずなんで挙動に違いは出ないと思うんですけど、intにする意味もなくて可読性悪いだけなんで直しました～

https://github.com/nakamo326/term3d/pull/10
